### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by andsju** [SebastianAlva99/case-3#1]
# Feedback
Godkänd: Nej, komplettering krävs

## Grundläggande krav
Applikationen ska

- [x] visa en tom länklista när sidan läses in
- [x] inte skapa ett listelement om det inte finns en url eller länktext angiven

En användare ska kunna

- [x] lägga till en länk
- [x] ta bort en länk
- [x] markera en länk (visuellt markera en länk item som favorit)

Grundläggande designkrav

- [] Figma-skiss
- [x] CSS: Någon del av koden skall använda sig av Flex eller Grid.
- [x] Ikonbibliotek: Använd er någon ikonbibliotek, t ex FontAwesome (https://fontawesome.com) eller IonIcons (https://ionic.io/ionicons)

- [x] Formulärfält ska valideras med inbyggda metoder i HTML (attribut som ex required). Det ska inte skapas ett listelement om inte det finns en länk angiven. Listan ska kunna fungera för en skärm.

- [x] Utvecklingen av applikationen ska finnas dokumenterad på GitHub. Du ska ha gjort minst 10 commits under projektet.

## Utmaningar

En användare ska kunna

- [x] få ett statusmeddelande om hen försöker lägga in en felaktig/förbjuden länk
- [] redigera en länk
- [x] flytta en länk uppåt eller nedåt i listan
- [] använd array för att lägga till länkar, ex initialt fylla en tom lista med några länkar
- [x] designa sidan så att den som besöker sidan ser vilken kategori av länkar som är tanken (film, musik, historia...)
- [] listan ska kunna fungera för mobil och skärm. (med media query)

### Kommentarer

Det finns flera saker i caset som jag tycker att du har löst på ett realtivt bra sätt. Applikationen i ditt projekt fungerar som det är tänkt, och du har antagit utmaningar - fint! 

Applikationen är versionshanterad, du har gjort commits över tid - bra! Här följer några kommentarer:

---

När du namnger filer så tänk på att vara konsekvent och följ en god namnstandard. Nu har du en fil som heter *länks.html*, och det sätt att namnge filer skiljer sig från andra filer i ditt projekt.  

---

Tänk också på att vara konsekvent då det gäller nanmngivning v klasser. I koden nedan använder du olika sätt att namnge. Inledande versal respektive camelCase.

```html
<ul class="Links" id="linkList">
```

För ett img element anger du med en klass med kebab-case, och ett värde för alt attributet med innehållet "Images". För den som inte uppfattar bilden visuellt blir den förklaringen märklig.

```html
<li><img src="" alt="Images" class="link-img">
```

---

Du har valt att man kan lägga till en bild i applikationen. Bilden som visas har fasta mått för höjd och bredd vilket innebär att bilder av olika proportiner inte visas korrekt. I case 2 gick vi igenom den typen av kod. 

```css
img {
    width: 500px;
    height: 300px;
    margin-left: 125px;
    padding: 8px;
    border: 1px solid #000000;
    border-radius: 8px;
    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    display: flex;
    align-items: center;
    margin-bottom: 20px;
    margin-top: 10px;
}
```

Det finns mer att säga om designen. Du har angett en margin-left för ett element, och jag vet inte varför du angett den? Se om du kan be Mattias hjälpa dig med att se över gränssnittet och den CSS som du du skapat. Genom att ange ett absolut värde på 570px blir det svårt att skapa responsiv design (vilket case 2 handlade om). 

```css
.main_länks {
    max-width: 800px;
    margin: 2em;
    margin-top: 150px;
    margin-left: 570px;
    padding: 1rem;
    background: rgb(189, 182, 182);
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.9);
    border-radius: 8px;
}
```

### Korrigering

I grundläggande krav finns angivet att det ska finnas med en FIGMA skiss. Jag kan inte se en sådan i ditt Git repo.

---

Du har klarat av mycket i det här caset. Sträva efter att förbättra din kod genom att följa en god namnstandard för filer, variabler, klasser etc. Det kommer större case efter hand i utbildningen och innan dess är mitt tips att du lägger tid på att hantera grundläggande tankar för att förstår programmering. I case 1 och 2 var namngivning ett grundläggande krav.

Korrigerat caset så att du når samtliga grundläggande krav. Se till att du uppdaterat Git repot, och kontakta mig därefter på Teams.
